#ifndef DRIVERBENCH_CORE_DB_METRICS_POLICY_H
#define DRIVERBENCH_CORE_DB_METRICS_POLICY_H

enum {
    DB_METRIC_SAMPLE_INITIAL_CAPACITY = 1024U,
    DB_METRIC_SAMPLE_MAX_CAPACITY = 1048576U,
};

#endif
