#ifndef DRIVERBENCH_DISPLAY_ENV_COMMON_H
#define DRIVERBENCH_DISPLAY_ENV_COMMON_H

#define DB_ENV_ALLOW_REMOTE_DISPLAY "DRIVERBENCH_ALLOW_REMOTE_DISPLAY"
#define DB_ENV_FPS_CAP "DRIVERBENCH_FPS_CAP"
#define DB_ENV_FRAMEBUFFER_HASH "DRIVERBENCH_FRAMEBUFFER_HASH"
#define DB_ENV_FRAME_LIMIT "DRIVERBENCH_FRAME_LIMIT"
#define DB_ENV_HASH_EVERY_FRAME "DRIVERBENCH_HASH_EVERY_FRAME"
#define DB_ENV_OFFSCREEN "DRIVERBENCH_OFFSCREEN"
#define DB_ENV_OFFSCREEN_FRAMES "DRIVERBENCH_OFFSCREEN_FRAMES"
#define DB_ENV_VSYNC "DRIVERBENCH_VSYNC"

#endif
