if(NOT DEFINED SOURCE_ROOT OR "${SOURCE_ROOT}" STREQUAL "")
  message(FATAL_ERROR "SOURCE_ROOT is required")
endif()
if(NOT DEFINED TEST_BINARY_DIR OR "${TEST_BINARY_DIR}" STREQUAL "")
  message(FATAL_ERROR "TEST_BINARY_DIR is required")
endif()
if(NOT DEFINED TEST_PROVIDER OR "${TEST_PROVIDER}" STREQUAL "")
  message(FATAL_ERROR "TEST_PROVIDER is required")
endif()
if(NOT DEFINED EXPECT_GLFW_AVAILABLE OR "${EXPECT_GLFW_AVAILABLE}" STREQUAL "")
  message(FATAL_ERROR "EXPECT_GLFW_AVAILABLE is required")
endif()
if(NOT DEFINED EXPECT_PROVIDER_RESOLVED OR
   "${EXPECT_PROVIDER_RESOLVED}" STREQUAL "")
  message(FATAL_ERROR "EXPECT_PROVIDER_RESOLVED is required")
endif()

file(REMOVE_RECURSE "${TEST_BINARY_DIR}")

set(DB_CONFIGURE_ARGS
  -S "${SOURCE_ROOT}"
  -B "${TEST_BINARY_DIR}"
  -DDB_GLFW_PROVIDER=${TEST_PROVIDER}
  -DDB_BUILD_VULKAN=OFF
  -DDB_BUILD_LINUX_KMS_ATOMIC_DISPLAY=OFF
  -DBUILD_TESTING=OFF
)

if(DEFINED TEST_GENERATOR AND NOT "${TEST_GENERATOR}" STREQUAL "")
  list(PREPEND DB_CONFIGURE_ARGS -G "${TEST_GENERATOR}")
endif()
if(DEFINED TEST_BUILD_TYPE AND NOT "${TEST_BUILD_TYPE}" STREQUAL "")
  list(APPEND DB_CONFIGURE_ARGS -DCMAKE_BUILD_TYPE=${TEST_BUILD_TYPE})
endif()
if(DEFINED TEST_C_COMPILER AND NOT "${TEST_C_COMPILER}" STREQUAL "")
  list(APPEND DB_CONFIGURE_ARGS -DCMAKE_C_COMPILER=${TEST_C_COMPILER})
endif()
if(DEFINED TEST_MAKE_PROGRAM AND NOT "${TEST_MAKE_PROGRAM}" STREQUAL "")
  list(APPEND DB_CONFIGURE_ARGS -DCMAKE_MAKE_PROGRAM=${TEST_MAKE_PROGRAM})
endif()

execute_process(
  COMMAND ${CMAKE_COMMAND} ${DB_CONFIGURE_ARGS}
  RESULT_VARIABLE DB_CONFIGURE_RESULT
  OUTPUT_VARIABLE DB_CONFIGURE_STDOUT
  ERROR_VARIABLE DB_CONFIGURE_STDERR
)
if(NOT DB_CONFIGURE_RESULT EQUAL 0)
  message(FATAL_ERROR
    "GLFW provider configure failed\nstdout:\n${DB_CONFIGURE_STDOUT}\nstderr:\n${DB_CONFIGURE_STDERR}")
endif()

set(DB_CACHE_FILE "${TEST_BINARY_DIR}/CMakeCache.txt")
if(NOT EXISTS "${DB_CACHE_FILE}")
  message(FATAL_ERROR "Expected cache file missing: ${DB_CACHE_FILE}")
endif()
file(READ "${DB_CACHE_FILE}" DB_CACHE_TEXT)

if(NOT DB_CACHE_TEXT MATCHES
       "DB_GLFW_AVAILABLE:INTERNAL=${EXPECT_GLFW_AVAILABLE}")
  message(FATAL_ERROR
    "Unexpected DB_GLFW_AVAILABLE for provider ${TEST_PROVIDER}\nexpected: ${EXPECT_GLFW_AVAILABLE}\ncache:\n${DB_CACHE_TEXT}")
endif()

if(NOT DB_CACHE_TEXT MATCHES
       "DB_GLFW_PROVIDER_RESOLVED:INTERNAL=${EXPECT_PROVIDER_RESOLVED}")
  message(FATAL_ERROR
    "Unexpected DB_GLFW_PROVIDER_RESOLVED for provider ${TEST_PROVIDER}\nexpected: ${EXPECT_PROVIDER_RESOLVED}\ncache:\n${DB_CACHE_TEXT}")
endif()
