function(db_configure_test_runtime_capabilities)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(DB_TEST_RUNTIME_GL1_OFFSCREEN_ARGS
      "${DB_DETERMINISM_GL1_OFFSCREEN_PREFIX} --benchmark-mode snake_grid ${DB_DETERMINISM_COMMON_ARGS} ${DB_DETERMINISM_HASH} ${DB_DETERMINISM_HASH_REPORT} ${DB_DETERMINISM_SNAKE_ARGS} --backbuffer-draw-mode full"
      PARENT_SCOPE
    )
    set(DB_TEST_RUNTIME_GL1_OFFSCREEN_HASH_CHECKS
      "${DB_DETERMINISM_GL1_OFFSCREEN_FULL_GOLDEN_HASH_CHECKS}"
      PARENT_SCOPE
    )
  else()
    set(DB_TEST_RUNTIME_GL1_OFFSCREEN_ARGS
      "${DB_DETERMINISM_GL1_OFFSCREEN_PREFIX} --benchmark-mode snake_grid ${DB_DETERMINISM_COMMON_ARGS} ${DB_DETERMINISM_HASH} ${DB_DETERMINISM_HASH_REPORT} ${DB_DETERMINISM_SNAKE_ARGS}"
      PARENT_SCOPE
    )
    set(DB_TEST_RUNTIME_GL1_OFFSCREEN_HASH_CHECKS
      "${DB_DETERMINISM_GL1_OFFSCREEN_DIRTY_GOLDEN_HASH_CHECKS}"
      PARENT_SCOPE
    )
  endif()

  if(APPLE)
    set(DB_TEST_RUNTIME_GL1_DIRTY_VARIANT_ARGS
      "${DB_DETERMINISM_GL1_OFFSCREEN_PREFIX} --benchmark-mode snake_grid ${DB_DETERMINISM_COMMON_ARGS} ${DB_DETERMINISM_HASH} ${DB_DETERMINISM_HASH_REPORT} ${DB_DETERMINISM_SNAKE_ARGS} --backbuffer-draw-mode dirty"
      PARENT_SCOPE
    )
    set(DB_TEST_RUNTIME_GL1_DIRTY_VARIANT_HASH_CHECKS
      "${DB_DETERMINISM_GL1_OFFSCREEN_DIRTY_GOLDEN_HASH_CHECKS}"
      PARENT_SCOPE
    )
  else()
    set(DB_TEST_RUNTIME_GL1_DIRTY_VARIANT_ARGS "" PARENT_SCOPE)
    set(DB_TEST_RUNTIME_GL1_DIRTY_VARIANT_HASH_CHECKS "" PARENT_SCOPE)
  endif()
endfunction()
