if(NOT DEFINED TEST_BIN)
  message(FATAL_ERROR "TEST_BIN is required")
endif()
if(NOT DEFINED TEST_EXIT_CODE)
  set(TEST_EXIT_CODE 0)
endif()
separate_arguments(TEST_ARGS)
execute_process(
  COMMAND ${TEST_BIN} ${TEST_ARGS}
  RESULT_VARIABLE TEST_RESULT
  OUTPUT_VARIABLE TEST_STDOUT
  ERROR_VARIABLE TEST_STDERR
)
set(TEST_OUTPUT "${TEST_STDOUT}${TEST_STDERR}")
if(NOT "${TEST_RESULT}" STREQUAL "${TEST_EXIT_CODE}")
  message(FATAL_ERROR
    "unexpected exit code\nexpected: ${TEST_EXIT_CODE}\nactual: ${TEST_RESULT}\noutput:\n${TEST_OUTPUT}")
endif()
if(DEFINED TEST_REQUIRED_PATTERNS AND NOT "${TEST_REQUIRED_PATTERNS}" STREQUAL "")
  string(REPLACE "," ";" TEST_REQUIRED_LIST "${TEST_REQUIRED_PATTERNS}")
  foreach(PATTERN IN LISTS TEST_REQUIRED_LIST)
    string(STRIP "${PATTERN}" PATTERN)
    if(PATTERN STREQUAL "")
      continue()
    endif()
    string(FIND "${TEST_OUTPUT}" "${PATTERN}" PATTERN_INDEX)
    if(PATTERN_INDEX EQUAL -1)
      message(FATAL_ERROR "missing required pattern '${PATTERN}'\noutput:\n${TEST_OUTPUT}")
    endif()
  endforeach()
endif()
if(DEFINED TEST_FORBIDDEN_PATTERNS AND NOT "${TEST_FORBIDDEN_PATTERNS}" STREQUAL "")
  string(REPLACE "," ";" TEST_FORBIDDEN_LIST "${TEST_FORBIDDEN_PATTERNS}")
  foreach(PATTERN IN LISTS TEST_FORBIDDEN_LIST)
    string(STRIP "${PATTERN}" PATTERN)
    if(PATTERN STREQUAL "")
      continue()
    endif()
    string(FIND "${TEST_OUTPUT}" "${PATTERN}" PATTERN_INDEX)
    if(NOT PATTERN_INDEX EQUAL -1)
      message(FATAL_ERROR "found forbidden pattern '${PATTERN}'\noutput:\n${TEST_OUTPUT}")
    endif()
  endforeach()
endif()
